image: eclipse-temurin:21.0.1_12-jdk-ubi9-minimal

pipelines:
   default:
   -  step:
         caches:
         - maven
         script:
         - /bin/sh mvnw install
         artifacts:
         - target/*.zip
   -  step:
         deployment: Production
         script:
         -  pipe: atlassian/ftp-deploy:0.6.0
            variables:
               USER: $FTP_USER
               PASSWORD: $FTP_PASSWORD
               SERVER: $FTP_HOST
               REMOTE_PATH: $FTP_REMOTE_PATH
               LOCAL_PATH: target/